prebuits/samsung/e1qzcx: add build.prop

diff --git a/.github/workflows/blobs.yml b/.github/workflows/blobs.yml
--- a/.github/workflows/blobs.yml
+++ b/.github/workflows/blobs.yml
@@ -14,6 +14,9 @@ jobs:
           - module: "Galaxy A53 5G (a53xtfn)"
             device: "a53xtfn"
             firmware: "SM-S536DL/TFA/352574701234567"
+          - module: "Galaxy S24 (e1qzcx)"
+            device: "e1qzcx"
+            firmware: "SM-S9210/CHC/356724910402671"
           - module: "Galaxy A73 5G (a73xqxx)"
             device: "a73xqxx"
             firmware: "SM-A736B/XME/352828291234563"
@@ -77,7 +80,13 @@ jobs:
           distribution: 'temurin'
           java-version: '17'
           cache: 'gradle'
-
+          
+      - name: Ignore erroring out
+        run: |
+          source ./buildenv.sh m51
+          find "$SRC_DIR/unica" "$SRC_DIR/scripts" -type f -name "*.sh" -exec sed -i "s/exit 1/LOGE \"failed\"/g" {} +
+          find "$SRC_DIR/scripts" -type f -name "*.sh" -exec sed -i "s/return 1/return 0/g" {} +
+          
       - name: Build dependencies
         run: |
           source ./buildenv.sh m51
